export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#455367",
        "primary-dim": "#1e4fa4",
        "on-tertiary-fixed": "#3e3a54",
        "on-tertiary": "#fcf7ff",
        "outline": "#6079b7",
        "tertiary-container": "#e2dbfd",
        "on-primary-fixed": "#003b8b",
        "surface-container-highest": "#d9e2ff",
        "primary-container": "#d9e2ff",
        "error-dim": "#4e0309",
        "secondary": "#526074",
        "tertiary-fixed": "#e2dbfd",
        "error-container": "#fe8983",
        "tertiary": "#605c78",
        "inverse-on-surface": "#959cb5",
        "on-primary-fixed-variant": "#2a58ae",
        "primary-fixed-dim": "#c4d4ff",
        "surface-container": "#eaedff",
        "secondary-fixed-dim": "#c7d5ed",
        "on-background": "#113069",
        "on-primary-container": "#1d4ea3",
        "inverse-surface": "#060e20",
        "surface-container-high": "#e2e7ff",
        "on-error-container": "#752121",
        "tertiary-dim": "#54506b",
        "surface-bright": "#faf8ff",
        "surface-variant": "#d9e2ff",
        "secondary-container": "#d5e3fc",
        "surface": "#faf8ff",
        "tertiary-fixed-dim": "#d4cdee",
        "on-error": "#fff7f6",
        "on-secondary-fixed": "#324053",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#79a1fc",
        "on-tertiary-container": "#514d68",
        "primary": "#2e5bb1",
        "surface-dim": "#cdd9ff",
        "primary-fixed": "#d9e2ff",
        "on-primary": "#f7f7ff",
        "outline-variant": "#98b1f2",
        "secondary-fixed": "#d5e3fc",
        "background": "#faf8ff",
        "on-surface-variant": "#445d99",
        "error": "#9f403d",
        "surface-tint": "#2e5bb1",
        "surface-container-low": "#f2f3ff",
        "on-tertiary-fixed-variant": "#5a5672",
        "on-secondary-fixed-variant": "#4e5c71",
        "secondary-dim": "#465468",
        "on-surface": "#113069",
        "on-secondary": "#f8f8ff"
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Manrope", "Inter"],
        label: ["Manrope", "Inter"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
